import React, {useState, useEffect, useCallback} from "react"
import {useNavigate} from 'react-router-dom';


const Context = React.createContext()

function ContextProvider(props) {
    const [languagesArray] = useState([{
        about: "About",
        whiteboardInstructions: "Try to type what is written here. Select some text and click the speaker icon to hear it or press ctrl + alt to see the word's definition (if you are on mobile, just press the word for about two seconds). More info on the about page.",
        title1: "What Is FullBucket?",
        part1: "When you are learning a new language, there are a lot of tools that can help you, like a dictionary to look up words, a text to speech technology to help you improve your ability to understand and pronounce certain words, and a place where you can practice both your reading and writing skills.",
        part2: "The problem is that those tools are scattered all around the internet. That's why I created FullBucket, to give you all the tools you need and let you focus on learning.",
        title2: "How Do I Use It?",
        part3: "Here are some features of the site and how to use them:",
        title3: "Type whatever you want",
        part4: "If you have any text that you would like not only to read but also to write, The whiteboard page will allow you to do so. Just click on the pen icon ",
        part5: " and paste your text to the input area. After that just click on the check icon ",
        part6: " and start typing...",
        title4: "Hear pronunciation",
        part7: "By selecting any text (",
        part8: "like this",
        part9: ") and clicking on the speaker icon ",
        part10: ", You'll be able to hear the word or sentence being read out loud. You can also change the text to speech voice and language by clicking on the cog icon ",
        part11: " and choosing an option from the drop-down menu. Voice options could be limited depending on the browser being used and you may need to change the TTS voice on your device's settings. You can learn more about the API used in this project ",
        part12: "here",
        title5: "See word definition",
        part13: "If you select (like shown above) a single word you can also see its definition by pressing Ctrl + Alt keys or by pressing it with your finger (if you are on a mobile device). When you do so, a card will appear with the word meaning and synonyms if available.",
        part14: "The API that provides the word's definition and synonyms is ",
        part15: "The Free Dictionary API",
        title6: "Spelling Practice",
        part16: "Spelling Practice helps you with your listening and writing abilities in English. There are around 500 sentences available containing the most used words in the English language. The way it works is simple, after reading the instructions on the Spelling Practice page press enter. You will hear the sentence being read out loud by your default TTS voice. After that just type the word that is missing in the sentence in front of you. You can hear the sentence again by pressing the speaker Icon ",
        part17: "You can still use the see word definition command on the Spelling Practice page."
    }, {
        about: "Sobre",
        whiteboardInstructions: "Tente digitar o que está escrito aqui. Selecione qualquer palavra e clique no ícone do alto-falante para ouvi-la ou pressione ctrl + alt para ver sua definição (em dispositivos móveis, basta pressionar a palavra por aproximadamente dois segundos). Mais detalhes na página 'sobre'.",
        title1: "O que é FullBucket?",
        part1: "Quando você está aprendendo um novo idioma, existem várias ferramentas que podem ajudá-lo, como um dicionário para procurar palavras, uma tecnologia de conversão de texto para fala para ajudá-lo a melhorar sua capacidade de entender e pronunciar certas palavras e um lugar onde você possa praticar suas habilidades de leitura e escrita.",
        part2: "O problema é que essas ferramentas estão espalhadas por varios cantos da internet. É por isso que criei o FullBucket, para dar a você todas as ferramentas que você precisa e permitir que você se concentre no aprendizado.",
        title2: "Como usar?",
        part3: "Aqui estão alguns recursos do site e como usá-los:",
        title3: "Digite o que quiser",
        part4: "Se você tiver algum texto que gostaria não apenas de ler, mas também de escrever, a página 'whiteboard' permitirá que você faça isso. Basta clicar no ícone da caneta ",
        part5: " e colar o texto na área de entrada. Depois disso, simplismente clique no ícone de confirmação ",
        part6: " e começe a digitar ...",
        title4: "Ouvir a pronúncia",
        part7: "Selecionando qualquer texto (",
        part8: "dessa forma",
        part9: ") e clicando no ícone do alto-falante ",
        part10: ", você poderá ouvir a palavra ou frase sendo lida em voz alta. Você também pode alterar a voz falada e o idioma clicando no ícone de engrenagem ",
        part11: " e escolhendo uma opção do menu. As opções de voz podem ser limitadas dependendo do navegador usado. Talvez seja preciso configurar as opções de voz no seu dispositivo. Para mais informações sobre o API usado neste projeto clique ",
        part12: "aqui",
        title5: "Veja a definição de palavras",
        part13: "Se você selecionar (como mostrado acima) uma única palavra, você também pode ver sua definição pressionando as teclas Ctrl + Alt ou a pressionando com o dedo (em dispositivos móveis). Ao fazer isso, o significado da palavra e sinônimos, se disponíveis, aparecerão.",
        part14: "O API que fornece as definições e os sinônimos das palavras é o ",
        part15: "Free Dictionary API",
        title6: "Prática de Ortografia",
        part16: "A prática ortográfica te ajuda com suas habilidades de escuta e escrita em inglês. São cerca de 500 frases disponíveis contendo as palavras mais utilizadas na língua inglesa. O funcionamento é simples, após ler as instruções na página 'Spelling Practice', pressione Enter. Você ouvirá a frase sendo lida em voz alta pela voz padrão do seu dispositivo. Depois disso, basta digitar a palavra que está faltando na frase em sua frente. É possível ouvir a frase novamente pressionando o ícone do alto-falante ",
        part17: "Você ainda pode usar o comando Ctrl + Alt para ver definição de palavras na página Prática de Ortografia."
    }])
    const [chosenLang, setChosenLang] = useState(JSON.parse(localStorage.getItem('lang')) || 0)
    const navigate = useNavigate()
    const [defaultSentences] = useState([
        { word: "building", sentence: "This building is so tall!"},
        { word: "action", sentence: "You next action is going to be critical."},
        { word: "full", sentence: "My work load is so full now."},
        { word: "model", sentence: "A great leader is a great model of how to do things."},
        { word: "join", sentence: "He wants to join the soccer team."},
        { word: "season", sentence: "Christmas is my favorite season!"},
        { word: "society", sentence: "Their society is holding a fund raiser."},
        { word: "because", sentence: "I'm going home because my mom needs me."},
        { word: "tax", sentence: "How much is the current income tax?"},
        { word: "director", sentence: "The director yelled 'Cut'!"},
        { word: "early", sentence: "I'm too early for my appointment."},
        { word: "position", sentence: "Please position your hand properly when drawing."},
        { word: "player", sentence: "That basketball player is cute."},
        { word: "agree", sentence: "I agree! He is cute!"},
        { word: "especially", sentence: "I especially like his blue eyes."},
        { word: "record", sentence: "Can we record the minutes of this meeting, please?"},
        { word: "pick", sentence: "Did you pick a color theme already?"},
        { word: "wear", sentence: "Is that what you're going to wear for the party?"},
        { word: "paper", sentence: "You can use a special paper for your invitations."},
        { word: "special", sentence: "Some special paper are even scented!"},
        { word: "space", sentence: "Please leave some space to write down your phone number."},
        { word: "ground", sentence: "The ground is shaking."},
        { word: "form", sentence: "A new island was formed after that big earthquake."},
        { word: "support", sentence: "I need your support for this project."},
        { word: "event", sentence: "We're holding a big event tonight."},
        { word: "official", sentence: "Our official wedding photos are out!"},
        { word: "whose", sentence: "Whose umbrella is this?"},
        { word: "matter", sentence: "What does it matter anyway?"},
        { word: "everyone", sentence: "Everyone thinks I stole that file."},
        { word: "center", sentence: "I hate being the center of attention."},
        { word: "couple", sentence: "The couple is on their honeymoon now."},
        { word: "site", sentence: "This site is so big!"},
        { word: "end", sentence: "It's the end of an era."},
        { word: "project", sentence: "This project file is due tomorrow."},
        { word: "hit", sentence: "He hit the burglar with a bat."},
        { word: "base", sentence: "All moms are their child's home base."},
        { word: "activity", sentence: "What musical activity can you suggest for my toddler?"},
        { word: "star", sentence: "My son can draw a star!"},
        { word: "table", sentence: "I saw him draw it while he was writing on the table."},
        { word: "need", sentence: "I need to enroll him to a good preschool."},
        { word: "court", sentence: "There's a basketball court near our house."},
        { word: "produce", sentence: "Fresh farm produce is the best."},
        { word: "eat", sentence: "I could eat that all day."},
        { word: "American", sentence: "My sister is dating an American."},
        { word: "teach", sentence: "I love to teach English lessons."},
        { word: "oil", sentence: "Could you buy me some cooking oil at the store?"},
        { word: "half", sentence: "Just half a liter please."},
        { word: "situation", sentence: "The situation is getting out of hand."},
        { word: "easy", sentence: "I thought you said this was going to be easy?"},
        { word: "cost", sentence: "The cost of fuel has increased!"},
        { word: "industry", sentence: "The fuel industry is hiking prices."},
        { word: "figure", sentence: "Will our government figure out how to fix this problem?"},
        { word: "face", sentence: "I can't bear to face this horrendous traffic again and again."},
        { word: "street", sentence: "Let's cross the street."},
        { word: "image", sentence: "There's an image of him stored inside my mind."},
        { word: "itself", sentence: "The bike itself is pretty awesome."},
        { word: "phone", sentence: "Plus, it has a phone holder."},
        { word: "either", sentence: "I either walk or commute to work."},
        { word: "data", sentence: "How can we simplify this data?"},
        { word: "cover", sentence: "Could you cover for me during emergencies?"},
        { word: "quite", sentence: "I'm quite satisfied with their work."},
        { word: "picture", sentence: "Picture this: a lake, a cabin, and lots of peace and quiet"},
        { word: "clear", sentence: "That picture is so clear inside my head."},
        { word: "practice", sentence: "Let's practice our dance number."},
        { word: "piece", sentence: "That's a piece of cake!"},
        { word: "land", sentence: "Their plane is going to land soon."},
        { word: "recent", sentence: "This is her most recent social media post."},
        { word: "describe", sentence: "Describe yourself in one word."},
        { word: "product", sentence: "This is my favorite product in their new line of cosmetics."},
        { word: "doctor", sentence: "The doctor is in."},
        { word: "wall", sentence: "Can you post this up on the wall?"},
        { word: "patient", sentence: "The patient is in so much pain now."},
        { word: "worker", sentence: "She's a factory worker."},
        { word: "news", sentence: "I saw that on the news."},
        { word: "test", sentence: "I have to pass this English test."},
        { word: "movie", sentence: "Let's watch a movie later."},
        { word: "certain", sentence: "There's a certain kind of magic in the air now."},
        { word: "north", sentence: "Santa lives up north."},
        { word: "love", sentence: " l love Christmas!"},
        { word: "personal", sentence: "This letter is very personal."},
        { word: "open", sentence: "Why did you open and read it?"},
        { word: "support", sentence: "Will you support him?"},
        { word: "simply", sentence: "I simply won't tolerate bad behavior."},
        { word: "third", sentence: "This is the third time you've lied to me."},
        { word: "technology", sentence: "Write about the advantages of technology."},
        { word: "catch", sentence: "Let's catch up soon, please!"},
        { word: "step", sentence: "Watch your step."},
        { word: "baby", sentence: "Her baby is so adorable."},
        { word: "computer", sentence: "Can you turn on the computer, please?"},
        { word: "type", sentence: "You need to type in your password."},
        { word: "attention", sentence: "Can I have your attention, please?"},
        { word: "draw", sentence: "Can you draw this for me?"},
        { word: "film", sentence: "That film is absolutely mind-blowing."},
        { word: "Republican", sentence: "He is a Republican candidate."},
        { word: "tree", sentence: "That tree has been there for generations."},
        { word: "source", sentence: "You are my source of strength."},
        { word: "red", sentence: "I'll wear a red dress tonight."},
        { word: "nearly", sentence: "He nearly died in that accident!"},
        { word: "organization", sentence: "Their organization is doing great things for street kids."},
        { word: "choose", sentence: "Let me choose a color."},
        { word: "cause", sentence: "We have to see the cause and effect of this experiment."},
        { word: "hair", sentence: "I'll cut my hair short for a change."},
        { word: "look", sentence: "Can you look at the items I bought?"},
        { word: "point", sentence: "What is the point of all this?"},
        { word: "century", sentence: "We're living in the 21st century, Mary."},
        { word: "evidence", sentence: "The evidence clearly shows that he is guilty."},
        { word: "window", sentence: "I'll buy window curtains next week."},
        { word: "difficult",  sentence: "Sometimes, life can be difficult."},
        { word: "listen", sentence: "You have to listen to your teacher."},
        { word: "soon", sentence: "I will launch my course soon."},
        { word: "culture", sentence: "I hope they understand our culture better."},
        { word: "billion", sentence: "My target is to have 1 billion dollars in my account by the end of the year."},
        { word: "chance", sentence: "Is there any chance that you can do this for me?"},
        { word: "brother", sentence: "My brother always have my back."},
        { word: "energy", sentence: "“Now put that energy into walking."},
        { word: "period", sentence: "They covered a period of twenty years."},
        { word: "course", sentence: "Have seen my course already?"},
        { word: "summer", sentence: "I'll go to the beach in summer."},
        { word: "less", sentence: "Sometimes, less is more."},
        { word: "realize", sentence: "I just realize that I have a meeting today."},
        { word: "hundred", sentence: "I have a hundred dollars that I can lend you."},
        { word: "available", sentence: "I am available to work on your project."},
        { word: "plant", sentence: "Plant a seed."},
        { word: "likely", sentence: "It was likely a deer trail."},
        { word: "opportunity", sentence: "It was the perfect opportunity to test her theory."},
        { word: "term", sentence: "I'm sure there's a Latin term for it."},
        { word: "short", sentence: "It was just a short stay at the hotel."},
        { word: "letter", sentence: "I already passed my letter of intent."},
        { word: "condition", sentence: "Do you know the condition I am in?"},
        { word: "choice", sentence: "I have no choice."},
        { word: "place", sentence: "Let's meet out at meeting place."},
        { word: "single", sentence: "I am a single parent."},
        { word: "rule", sentence: "It's the rule of the law."},
        { word: "daughter", sentence: "My daughter knows how to read now."},
        { word: "administration", sentence: "I will take this up with the administration."},
        { word: "south", sentence: "I am headed south."},
        { word: "husband", sentence: "My husband just bought me a ring for my birthday."},
        { word: "Congress", sentence: "It will be debated at the Congress."},
        { word: "floor", sentence: "She is our floor manager."},
        { word: "campaign", sentence: "I handled their election campaign."},
        { word: "material", sentence: "She had nothing material to report."},
        { word: "population", sentence: "The population of the nearest big city was growing."},
        { word: "well", sentence: "I wish you well."},
        { word: "call", sentence: " I am going to call the bank."},
        { word: "economy", sentence: "The economy is booming."},
        { word:  "medical", sentence: "She needs medical assistance."},
        { word: "hospital", sentence: "I'll take her to the nearest hospital."},
        { word: "church", sentence: "I saw you in church last Sunday."},
        { word: "close",  sentence: "Please close the door."},
        { word: "thousand", sentence: "There are a thousand reasons to learn English!"},
        { word: "risk", sentence: "Taking a risk can be rewarding."},
        { word: "current", sentence: "What is your current address?"},
        { word: "fire", sentence: "Make sure your smoke alarm works in case of fire."},
        { word: "future", sentence: "The future is full of hope."},
        { word: "wrong", sentence: "That is the wrong answer."},
        { word: "involve", sentence: "We need to involve the police."},
        { word: "defense", sentence: "What is your defense or reason you did this?"},
        { word: "anyone", sentence: "Does anyone know the answer?"},
        { word: "increase", sentence: "Let's increase your test score."},
        { word: "security", sentence: "Some apartment buildings have security."},
        { word: "bank", sentence: "I need to go to the bank to withdraw some money."},
        { word: "myself", sentence: "I can clean up by myself."},
        { word: "certainly", sentence: "I can certainly help clean up."},
        { word: "west", sentence: "If you drive West, you will arrive in California."},
        { word: "sport", sentence: "My favorite sport is soccer."},
        { word: "board", sentence: "Can you see the board?"},
        { word: "seek", sentence: "Seek and you will find."},
        { word: "per", sentence: "Lobster is $20 per pound."},
        { word: "subject", sentence: "My favorite subject is English!"},
        { word: "officer", sentence: "Where can I find a police officer?"},
        { word: "private", sentence: "This is a private party."},
        { word: "rest", sentence: "Let's take a 15 minute rest."},
        { word: "behavior", sentence: "This dog's behavior is excellent."},
        { word: "deal", sentence: "A used car can be a good deal."},
        { word: "performance", sentence: "Your performance can be affected by your sleep."},
        { word: "fight", sentence: "I don't want to fight with you."},
        { word: "throw", sentence: "Throw me the ball!"},
        { word: "top", sentence: "You are a top student."},
        { word: "quickly", sentence: "Let's finish reading this quickly."},
        { word: "past", sentence: "In the past, my English was not as good as it is today."},
        { word: "goal", sentence: "My goal is to speak English fluently."},
        { word: "second", sentence: "My second goal is to increase my confidence."},
        { word: "bed", sentence: "I go to bed around 10pm."},
        { word: "order", sentence: "I would like to order a book."},
        { word: "author", sentence: "The author of this series is world-famous."},
        { word: "fill", sentence: "I need to fill (up) my gas tank."},
        { word: "represent", sentence: "I represent my family."},
        { word: "focus", sentence: "Turn off your phone and the TV and focus on your studies!"},
        { word: "foreign", sentence: "It's great having foreign friends."},
        { word: "drop", sentence: "Please don't drop the eggs!"},
        { word: "plan", sentence: "Let's make a plan."},
        { word: "blood", sentence: "The hospital needs people to give blood."},
        { word: "upon", sentence: "Once upon a time, a princess lived in a castle."},
        { word: "agency", sentence: "Let's contract an agency to help with marketing."},
        { word: "push", sentence: "The door says 'push,' not 'pull'."},
        { word: "nature", sentence: "I love walking in nature!"},
        { word: "color", sentence: "My favorite color is blue."},
        { word: "no", sentence: "'No' is one of the shortest complete sentences."},
        { word: "recently", sentence: "I cleaned the bathroom most recently, so I think it's your turn this time."},
        { word: "store", sentence: "I'm going to the store to buy some bread."},
        { word: "reduce", sentence: "Reduce, reuse, and recycle are the ways to help the environment."},
        { word: "sound", sentence: "I like the sound of wind chimes."},
        { word: "note", sentence: "Please take notes during the lesson."},
        { word: "fine", sentence: "I feel fine."},
        { word: "before", sentence: "Before the movie, let's buy popcorn!"},
        { word: "near", sentence: "Near, far, wherever you are, I do believe that the heart goes on."},
        { word: "movement", sentence: "The environmental movement is an international movement."},
        { word: "page", sentence: "Please turn to page 62."},
        { word: "enter", sentence: "You can enter the building on the left."},
        { word: "share", sentence: "Let me share my idea."},
        { word: "than", sentence: "Ice cream has more calories than water."},
        { word: "common", sentence: "Most people can find something in common with each other."},
        { word: "poor", sentence: "We had a poor harvest this year because it was so dry."},
        { word: "other", sentence: "This pen doesn't work, try the other one."},
        { word: "natural", sentence: "This cleaner is natural, there aren't any chemicals in it."},
        { word: "race", sentence: "We watched the car race on TV."},
        { word: "concern", sentence: "Thank you for your concern, but I'm fine."},
        { word: "series", sentence: "What is your favorite TV series?"},
        { word: "significant", sentence: "His job earns a significant amount of money."},
        { word: "similar", sentence: "These earrings don't match, but they are similar."},
        { word: "hot", sentence: "Don't touch the stove, it's still hot."},
        { word: "language", sentence: "Learning a new language is fun."},
        { word: "each", sentence: "Put a flower in each vase."},
        { word: "usually", sentence: "I usually shop at the corner store."},
        { word: "response", sentence: "I didn't expect his response to come so soon."},
        { word: "dead", sentence: "My phone is dead, let me charge it."},
        { word: "rise", sentence: "The sun will rise at 7:00 a.m."},
        { word: "animal", sentence: "What kind of animal is that?"},
        { word: "factor", sentence: "Heredity is a factor in your overall health."},
        { word: "decade", sentence: "I've lived in this city for over a decade."},
        { word: "article", sentence: "Did you read that newspaper article?"},
        { word: "shoot", sentence: "He wants to shoot arrows at the target."},
        { word: "east", sentence: "Drive east for three miles."},
        { word: "save", sentence: "I save all my cans for recycling."},
        { word: "seven", sentence: "There are seven slices of pie left."},
        { word: "artist", sentence: "Taylor Swift is a recording artist."},
        { word: "away", sentence: "I wish that mosquito would go away."},
        { word: "scene", sentence: "He painted a colorful street scene."},
        { word: "stock", sentence: "That shop has a good stock of postcards."},
        { word: "career", sentence: "Retail sales is a good career for some people."},
        { word: "despite", sentence: "Despite the rain, we will still have the picnic."},
        { word: "central", sentence: "There is good shopping in central London."},
        { word: "eight", sentence: "That recipe takes eight cups of flour."},
        { word: "thus", sentence: "We haven't had any problems thus far."},
        { word: "treatment", sentence: "I will propose a treatment plan for your injury."},
        { word: "beyond", sentence: "The town is just beyond those mountains."},
        { word: "happy", sentence: "Kittens make me happy."},
        { word: "exactly", sentence: "Use exactly one teaspoon of salt in that recipe."},
        { word: "protect", sentence: "A coat will protect you from the cold weather."},
        { word: "approach", sentence: "The cat slowly approached the bird."},
        { word: "lie", sentence: "Teach your children not to lie."},
        { word: "size", sentence: "What size is that shirt"},
        { word: "dog", sentence: "Do you think a dog is a good pet?"},
        { word: "fund", sentence: "I have a savings fund for college."},
        { word: "serious", sentence: "She is so serious, she never laughs."},
        { word: "occur", sentence: "Strange things occur in that empty house."},
        { word: "media", sentence: "That issue has been discussed in the media."},
        { word: "ready", sentence: "Are you ready to leave for work?"},
        { word: "sign", sentence: "That store needs a bigger sign."},
        { word: "thought", sentence: "I'll have to give it some thought."},
        { word: "list", sentence: "I made a list of things to do."},
        { word: "individual", sentence: "You can buy an individual or group membership."},
        { word: "simple", sentence: "The appliance comes with simple instructions."},
        { word: "quality", sentence: "I paid a little more for quality shoes."},
        { word: "pressure", sentence: "There is no pressure to finish right now."},
        { word: "accept", sentence: "Will you accept my credit card?"},
        { word: "answer", sentence: "Give me your answer by noon tomorrow."},
        { word: "hard", sentence: "That test was very hard."},
        { word: "resource", sentence: "The library has many online resources."},
        { word: "identify", sentence: "I can't identify that plant."},
        { word: "left", sentence: "The door is on your left as you approach."},
        { word: "meeting", sentence: "We'll have a staff meeting after lunch."},
        { word: "determine", sentence: "Eye color is genetically determined."},
        { word: "prepare", sentence: "I'll prepare breakfast tomorrow."},
        { word: "disease", sentence: "Face masks help prevent disease."},
        { word: "whatever", sentence: "Choose whatever flavor you like the best."},
        { word: "success", sentence: "Failure is the back door to success."},
        { word: "argue", sentence: "It's not a good idea to argue with your boss."},
        { word: "cup", sentence: "Would you like a cup of coffee?"},
        { word: "particularly", sentence: "It's not particularly hot outside, just warm."},
        { word: "amount", sentence: "It take a large amount of food to feed an elephant."},
        { word: "ability", sentence: "He has the ability to explain things well."},
        { word: "staff", sentence: "There are five people on staff here."},
        { word: "recognize", sentence: "Do you recognize the person in this photo?"},
        { word: "indicate", sentence: "Her reply indicated that she understood."},
        { word: "character", sentence: "You can trust people of good character."},
        { word: "growth", sentence: "The company has seen strong growth this quarter."},
        { word: "loss", sentence: "The farmer suffered heavy losses after the storm."},
        { word: "degree", sentence: "Set the oven to 300 degrees."},
        { word: "wonder", sentence: "I wonder if the Bulls will win the game."},
        { word: "attack", sentence: "The army will attack at dawn."},
        { word: "herself", sentence: "She bought herself a new coat."},
        { word: "region", sentence: "What internet services are in your region?"},
        { word: "television", sentence: "I don't watch much television."},
        { word: "box", sentence: "I packed my dishes in a strong box."},
        { word: "TV", sentence: "There is a good movie on TV tonight."},
        { word: "training", sentence: "The company will pay for your training."},
        { word: "pretty", sentence: "That is a pretty dress."},
        { word: "trade", sentence: "The stock market traded lower today."},
        { word: "deal", sentence: "I got a good deal at the store."},
        { word: "election", sentence: "Who do you think will win the election?"},
        { word: "everybody", sentence: "Everybody likes ice cream."},
        { word: "physical", sentence: "Keep a physical distance of six feet."},
        { word: "lay", sentence: "Lay the baby in her crib, please."},
        { word: "general", sentence: "My general impression of the restaurant was good."},
        { word: "feeling", sentence: "I have a good feeling about this."},
        { word: "standard", sentence: "The standard fee is $10.00."},
        { word: "bill", sentence: "The electrician will send me a bill."},
        { word: "message", sentence: "You have a text message on your phone."},
        { word: "fail", sentence: "I fail to see what is so funny about that."},
        { word: "outside", sentence: "The cat goes outside sometimes."},
        { word: "arrive", sentence: "When will your plane arrive?"},
        { word: "analysis", sentence: "I'll give you my analysis when I've seen everything."},
        { word: "benefit", sentence: "There are many health benefits to quinoa."},
        { word: "name", sentence: "What's your name?"},
        { word: "sex", sentence: "Do you know the sex of your baby yet?"},
        { word: "forward", sentence: "Move the car forward a few feet."},
        { word: "lawyer", sentence: "My lawyer helped me write a will."},
        { word: "present", sentence: "If everyone is present, the meeting can begin."},
        { word: "section", sentence: "What section of the stadium are you sitting in?"},
        { word: "environmental", sentence: "Environmental issues are in the news."},
        { word: "glass", sentence: "Glass is much heavier than plastic."},
        { word: "answer", sentence: "Could you answer a question for me?"},
        { word: "skill", sentence: "His best skill is woodworking."},
        { word: "sister", sentence: "My sister lives close to me."},
        { word: "PM", sentence: "The movie starts at 7:30 PM."},
        { word: "professor", sentence: "Dr. Smith is my favorite professor."},
        { word: "operation", sentence: "The mining operation employs thousands of people."},
        { word: "financial", sentence: "I keep my accounts at my financial institution."},
        { word: "crime", sentence: "The police fight crime."},
        { word: "stage", sentence: "A caterpillar is the larval stage of a butterfly."},
        { word: "ok", sentence: "Would it be ok to eat out tonight?"},
        { word: "compare", sentence: "We should compare cars before we buy one."},
        { word: "authority", sentence: "City authorities make the local laws."},
        { word: "miss", sentence: "I miss you, when will I see you again?"},
        { word: "design", sentence: "We need to design a new logo."},
        { word: "sort", sentence: "Let's sort these beads according to color."},
        { word: "one", sentence: "I only have one cat."},
        { word: "act", sentence: "I'll act on your information today."},
        { word: "ten", sentence: "The baby counted her ten toes."},
        { word: "knowledge", sentence: "Do you have the knowledge to fix that?"},
        { word: "gun", sentence: "Gun ownership is a controversial topic."},
        { word: "station", sentence: "There is a train station close to my house."},
        { word: "blue", sentence: "My favorite color is blue."},
        { word: "state", sentence: "After the accident I was in a state of shock."},
        { word: "strategy", sentence: "Our new corporate strategy is written here."},
        { word: "little", sentence: "I prefer little cars."},
        { word: "clearly", sentence: "The instructions were clearly written."},
        { word: "discuss", sentence: "We'll discuss that at the meeting."},
        { word: "indeed", sentence: "Your mother does indeed have hearing loss."},
        { word: "force", sentence: "It takes a lot of force to open that door."},
        { word: "truth", sentence: "Please tell me the truth."},
        { word: "song", sentence: "That's a beautiful song."},
        { word: "example", sentence: "I need an example of that grammar point, please."},
        { word: "democratic", sentence: "Does Australia have a democratic government?"},
        { word: "check", sentence: "Please check my work to be sure it's correct."},
        { word: "environment", sentence: "We live in a healthy environment."},
        { word: "leg", sentence: "The boy broke his leg."},
        { word: "dark", sentence: "Turn on the light, it's dark in here."},
        { word: "public", sentence: "Masks must be worn in public places."},
        { word: "various", sentence: "That rug comes in various shades of gray."},
        { word: "rather", sentence: "Would you rather have a hamburger than a hot dog?"},
        { word: "laugh", sentence: "That movie always makes me laugh."},
        { word: "guess", sentence: "If you don't know, just guess."},
        { word: "executive", sentence: "The company's executives are paid well."},
        { word: "set", sentence: "Set the glass on the table, please."},
        { word: "study", sentence: "He needs to study for the test."},
        { word: "prove", sentence: "The employee proved his worth."},
        { word: "hang", sentence: "Please hang your coat on the hook."},
        { word: "entire", sentence: "He ate the entire meal in 10 minutes."},
        { word: "rock", sentence: "There are decorative rocks in the garden."},
        { word: "design", sentence: "The windows don't open by design."},
        { word: "enough", sentence: "Have you had enough coffee?"},
        { word: "forget", sentence: "Don't forget to stop at the store."},
        { word: "since", sentence: "She hasn't eaten since yesterday."},
        { word: "claim", sentence: "I made an insurance claim for my car accident."},
        { word: "note", sentence: "Leave me a note if you're going to be late."},
        { word: "remove", sentence: "Remove the cookies from the oven."},
        { word: "manager", sentence: "The manager will look at your application."},
        { word: "help", sentence: "Could you help me move this table?"},
        { word: "close", sentence: "Close the door, please."},
        { word: "sound", sentence: "The dog did not make a sound."},
        { word: "enjoy", sentence: "I enjoy soda."},
        { word: "network", sentence: "Band is the name of our internet network."},
        { word: "legal", sentence: "The legal documents need to be signed."},
        { word: "religious", sentence: "She is very religious, she attends church weekly."},
        { word: "cold", sentence: "My feet are cold."},
        { word: "form", sentence: "Please fill out this application form."},
        { word: "final", sentence: "The divorce was final last month."},
        { word: "main", sentence: "The main problem is a lack of money."},
        { word: "science", sentence: "He studies health science at the university."},
        { word: "green", sentence: "The grass is green."},
        { word: "memory", sentence: "He has a good memory."},
        { word: "card", sentence: "They sent me a card for my birthday."},
        { word: "above", sentence: "Look on the shelf above the sink."},
        { word: "seat", sentence: "That's a comfortable seat."},
        { word: "cell", sentence: "Your body is made of millions of cells."},
        { word: "establish", sentence: "They established their business in 1942."},
        { word: "nice", sentence: "That's a very nice car."},
        { word: "trial", sentence: "They are employing her on a trial basis."},
        { word: "expert", sentence: "Matt is an IT expert."},
        { word: "that", sentence: "Did you see that movie?"},
        { word: "spring", sentence: "Spring is the most beautiful season."},
        { word: "firm", sentence: "Her 'no' was very firm, she won't change her mind."},
        { word: "Democrat", sentence: "The Democrats control the Senate."},
        { word: "radio", sentence: "I listen to the radio in the car."},
        { word: "visit", sentence: "We visited the museum today."},
        { word: "management", sentence: "That store has good management."},
        { word: "care", sentence: "She cares for her mother at home."},
        { word: "avoid", sentence: "You should avoid poison ivy."},
        { word: "imagine", sentence: "Can you imagine if pigs could fly?"},
        { word: "tonight", sentence: "Would you like to go out tonight?"},
        { word: "huge", sentence: "That truck is huge!"},
        { word: "ball", sentence: "He threw the ball to the dog."},
        { word: "no", sentence: "I said 'no', please don't ask again."},
        { word: "close", sentence: "Close the window, please."},
        { word: "finish", sentence: "Did you finish your homework?"},
        { word: "yourself", sentence: "You gave yourself a haircut?"},
        { word: "talk", sentence: "He talks a lot."},
        { word: "theory", sentence: "In theory, that's a good plan."},
        { word: "impact", sentence: "The drought had a big impact on the crops."},
        { word: "respond", sentence: "He hasn't responded to my text yet."},
        { word: "statement", sentence: "The police chief gave a statement to the media."},
        { word: "maintain", sentence: "Exercise helps you maintain a healthy weight."},
        { word: "charge", sentence: "I need to charge my phone."},
        { word: "popular", sentence: "That's a popular restaurant."},
        { word: "traditional", sentence: "They serve traditional Italian food there."},
        { word: "onto", sentence: "Jump onto the boat and we'll go fishing."},
        { word: "reveal", sentence: "Washing off the dirt revealed the boy's skinned knee."},
        { word: "direction", sentence: "What direction is the city from here?"},
        { word: "weapon", sentence: "No weapons are allowed in government buildings."},
        { word: "employee", sentence: "That store only has three employees."},
        { word: "cultural", sentence: "There is cultural significance to those old ruins."},
        { word: "contain", sentence: "The carton contains a dozen egges."},
        { word: "peace", sentence: "World leaders gathered for peace talks."},
        { word: "head", sentence: "My head hurts."},
        { word: "control", sentence: "Keep control of the car."},
        { word: "base", sentence: "The glass has a heavy base so it won't fall over."},
        { word: "pain", sentence: "I have chest pain."},
        { word: "apply", sentence: "Maria applied for the job."},
        { word: "play", sentence: "The children play at the park."},
        { word: "measure", sentence: "Measure twice, cut once."},
        { word: "wide", sentence: "The doorway was very wide."},
        { word: "shake", sentence: "Don't shake the can of soda."},
        { word: "fly", sentence: "We can fly to France next year."},
        { word: "interview", sentence: "My job interview went well."},
        { word: "manage", sentence: "Did you manage to find the keys?"},
        { word: "chair", sentence: "The table has six matching chairs."},
        { word: "fish", sentence: "I don't enjoy eating fish."},
        { word: "particular", sentence: "That particular style looks good on you."},
        { word: "camera", sentence: "I use the camera on my phone."},
        { word: "structure", sentence: "The building's structure is solid."},
        { word: "politics", sentence: "Mitch is very active in politics."},
        { word: "perform", sentence: "The singer will perform tonight."},
        { word: "bit", sentence: "It rained a little bit last night."},
        { word: "weight", sentence: "Keep track of your pet's weight."},
        { word: "suddenly", sentence: "The storm came up suddenly."},
        { word: "discover", sentence: "You'll discover treasures at that thrift store."},
        { word: "candidate", sentence: "There are ten candidates for the position."},
        { word: "top", sentence: "The flag flies on the top of that building."},
        { word: "production", sentence: "Factory production has improved over the summer."},
        { word: "treat", sentence: "Give yourself a treat for a job well done."},
        { word: "trip", sentence: "We are taking a trip to Florida in January."},
        { word: "evening", sentence: "I'm staying home this evening."},
        { word: "affect", sentence: "My bank account will affect how much I can buy."},
        { word: "inside", sentence: "The cat stays inside."},
        { word: "conference", sentence: "There will be expert presenters at the conference."},
        { word: "unit", sentence: "A foot is a unit of measure."},
        { word: "best", sentence: "Those are the best glasses to buy."},
        { word: "style", sentence: "My dress is out of style."},
        { word: "adult", sentence: "Adults pay full price, but children are free."},
        { word: "worry", sentence: "Don't worry about tomorrow."},
        { word: "range", sentence: "y doctor offered me a range of options"},
        { word: "mention", sentence: "Can you mention me in your story?"},
        { word: "rather", sentence: "Rather than focusing on the bad things, let's be grateful for the good things."},
        { word: "far", sentence: "I don't want to move far from my family."},
        { word: "deep", sentence: "That poem about life is deep."},
        { word: "front", sentence: "Please face front."},
        { word: "edge", sentence: "Please do not stand so close to the edge of the cliff."},
        { word: "individual", sentence: "These potato chips are in an individual serving size package."},
        { word: "specific", sentence: "Could you be more specific?"},
        { word: "writer", sentence: "You are a good writer."},
        { word: "trouble", sentence: "Stay out of trouble."},
        { word: "necessary", sentence: "It is necessary to sleep."},
        { word: "throughout", sentence: "Throughout my life I have always enjoyed reading."},
        { word: "challenge", sentence: "I challenge you to do better."},
        { word: "fear", sentence: "Do you have any fears?"},
        { word: "shoulder", sentence: "You do not have to shoulder all the work on your own."},
        { word: "institution", sentence: "Have you attended any institution of higher learning?"},
        { word: "middle", sentence: "I am a middle child with one older brother and one younger sister."},
        { word: "sea", sentence: "I want to sail the seven seas."},
        { word: "dream", sentence: "I have a dream."},
        { word: "bar", sentence: "A bar is a place where alcohol is served."},
        { word: "beautiful", sentence: "You are beautiful."},
        { word: "property", sentence: "Do you own property, like a house?"},
        { word: "instead", sentence: "Instead of eating cake I will have fruit."},
        { word: "improve", sentence: "I am always looking for ways to improve."},
        { word: "stuff", sentence: "When I moved, I realized I have a lot of stuff!"},
        { word: "claim", sentence: "I claim to be a fast reader, but actually I am average."},
        { word: "international", sentence: "Their brand has gone international!"}
    ])
    const [customSentences, setCustomSentences] = useState(JSON.parse(localStorage.getItem('customSentencesArray')) || [])
    const [isCustom, setIsCustom] = useState(false)
    const [showSPOptions, setShowSPOptions] = useState(false)
    const [selection, setSelection] = useState('')
    const [currentCustomSentence, setCurrentCustomSentence] = useState(0)

    useEffect( () => {
        localStorage.setItem('lang', JSON.stringify(chosenLang))
    }, [chosenLang])

    useEffect( () => {
        localStorage.setItem('customSentencesArray', JSON.stringify(customSentences))
    }, [customSentences])

    function makingFlashCard(text) {
        if (text !== ' ' && text) {
            const splitedText = text.split(' ')
            const flashCards = splitedText.map( (word) => {
                return { word: word , sentence: text}
            })
            /* setCustomSentences(prev => [...prev, {sentencesArrays: flashCards, isCustom: true}]) */
            setCustomSentences(flashCards)
            /* setCurrentSentences(prev => ({sentencesArrays: {...prev.sentencesArrays, custom: flashCards}, isCustom: true})) */
           /*  handleOnClick() */
        }
    }

    function callSPPanel(text) {
        console.log("text", typeof text)
        if (text !== ' ' || text !== '' ) {
            setShowSPOptions(prev => !prev)
            setSelection(text)
        }
    }

    function submitCustomSP(words) {
        const flashCards = words.map( (word) => {
            return { word: word, sentence: selection}
        } )

        setCustomSentences(prev => {
            return [...prev, {array: flashCards, indexNum: customSentences.length + 1}]
        })
        setIsCustom(true)
        setCurrentCustomSentence(customSentences.length)
        /* setCurrentSentences(prev => ({sentencesArrays: {...prev.sentencesArrays, custom: flashCards}, isCustom: true})) */
        handleOnClick()
    }
    
    function switchDecks(i, callbackFunc) {
        setCurrentCustomSentence(i)
        setIsCustom(true)
        return customSentences[i]
    }

    function deleteDeck(e, index) {
        e.stopPropagation()
        setCustomSentences(prev => {
           return prev.filter( (obj, i) => {
               return i !== index
            } )
        })
        goToDefaultDeck()
    }

    function goToDefaultDeck() {
        setIsCustom(false)
    }

    console.log('customSentences', customSentences)

    const handleOnClick = useCallback(() => navigate('/spelling', {replace: true}), [navigate])

    const chosenSentences = isCustom ? customSentences[currentCustomSentence] : {array: defaultSentences, indexNum: 0}
    return (
        <Context.Provider value={{
            lang: languagesArray[chosenLang], 
            setChosenLang: setChosenLang, 
            chosenLang: chosenLang, 
            languagesArray, 
            chosenSentences, 
            isCustom, 
            customSentences,
            makingFlashCard,
            callSPPanel,
            showSPOptions,
            setShowSPOptions,
            selection,
            submitCustomSP,
            defaultSentences,
            switchDecks,
            deleteDeck,
            goToDefaultDeck
        }}>
            {props.children}
        </Context.Provider>
    )
}

export {ContextProvider, Context} 

